### ISSUE TITLE
Correctly handle command chaining in the default startup script and document it.

### ISSUE THREAD

**Issue by Soulou** [Scalingo/nginx-buildpack#21]
For instance, it should be possible to have the following Procfile:

```
web: bin/run npm start
```

This would start nginx then a node application, and when a termination signal is received, both process should stop gracefully to prevent breaking requests.

**Comment by Soulou** [comment]
Tell https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700034813 when done

**Comment by EtienneM** [comment]
This is supported by the Heroku buildpack. We may want to take inspiration from it.

https://github.com/heroku/heroku-buildpack-nginx

**Comment by ipfaze** [comment]
Too old, closing it.
