### ISSUE TITLE
Verify client config does not work

### ISSUE THREAD

**Issue by Tyflomate** [Scalingo/nginx-buildpack#32]
Hello ! I'm trying to use your buildpack to create a RP which will ask our users for a certificates connection but it does not seem to work. When i access the scalingo app threw my navigator it does not ask for a certificate. Here is my  `nginx.conf` in root:
```
ssl_client_certificate /app/client-ca.crt;
ssl_certificate /app/app.crt;
ssl_certificate_key /app/app.key;
ssl_verify_client optional;
ssl_session_timeout 5s;
ssl_session_tickets off;
ssl_session_cache off;
ssl_prefer_server_ciphers on;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_verify_depth 3;
client_max_body_size 200M;

resolver 8.8.8.8 ipv6=off;

location / {
    proxy_set_header "X-TLS-Serial" $ssl_client_serial;
    proxy_set_header "X-TLS-Verify" $ssl_client_verify;
    proxy_set_header "X-TLS-DN" $ssl_client_s_dn;
    proxy_set_header "X-TLS-DN-Legacy" $ssl_client_s_dn_legacy;
    proxy_set_header "X-TLS-Fingerprint" $ssl_client_fingerprint;
    proxy_set_header "X-TLS-Cert" $ssl_client_cert;
    proxy_set_header "X-TLS-Espaced-Cert" $ssl_client_escaped_cert;
    proxy_pass https://le-registre-api-dev.osc-fr1.scalingo.io;
}

error_page   500 502 503 504  /50x.html;
location = /50x.html {
    root   html;
}
```
Nginx version: 1.18.0

I took a look inside my container and the bin/run script. It creates the nginx.conf from an erb file which should include my config when ran. In the config created from it there is no sign of mine and it is supposed to be copied in `vendor/nginx/conf/site.conf` but this file does not exist on my container. I tried to run the script by hand, just being curious, and i had an error:
```
nginx: [emerg] invalid port in "0" of the "listen" directive in /app/vendor/nginx/conf/nginx.conf:74
Boot failed: nginx
```
There is a running version of this architecture on openshift but where are trying to migrate. Let me know if there is anything more I need to tell you. Hope you can help !

**Comment by Tyflomate** [comment]
Hello @EtienneM , as the most recent contributor in this repository, maybe you could help ? Tahnks a lot !

**Comment by johnsudaar** [comment]
Hi there,

The issue in your local development is that you do not define a `PORT` environment variable.
If you want to run the `bin/run` script in a development environment you'll need to export that variable.

For example:
```
export PORT=1234
bin/run &
```

To answer directly your question, Client TLS authentication is not possible on Scalingo because our reverse proxies are the one handling TLS termination thus the nginx running on your application will only see HTTP connection without any certificate.

This is a known limitation of the platform and unfortunately there's no known workaround.

**Comment by Tyflomate** [comment]
Hello ! Thank you for your response. I tried adding the environment variable PORT but scalingo says that it is reserved so i can't specify something. Anyway, if I can't use ssl_verify_client in scalingo, there is no use to this, thank you for your help :+1:

**Comment by johnsudaar** [comment]
The PORT environment just needs to be added when you try the script by hand.
It was in response to the following part of your ticket:

> I tried to run the script by hand, just being curious, and i had an error:

You do not need to inject the port on real Scalingo apps since this variable will be automatically injected by the platform.
