### ISSUE TITLE
limit_req_zone statement in http block for DOS protection

### ISSUE THREAD

**Issue by davidwittenbrink** [Scalingo/nginx-buildpack#5]
Hi!

We would like to introduce [nginx rate limiting](https://www.nginx.com/blog/rate-limiting-nginx/) to our load balancer. [According to the docs](http://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_zone) the necessary `limit_req_zone` statement can only be applied in a `http` context while the actual usage of the zone through the `limit_req` statement can be used inside `server` and `location` blocks.

Do you have any suggestions how this could be implemented?

**Comment by Soulou** [comment]
Such thing is possible in the dev branch, the README explains how to add http leveled instructions.

https://github.com/Scalingo/nginx-buildpack/tree/dev

The `dev` branch will be merged into master at some point.
